
services:
  web:
    container_name: antonio-flask
    hostname: antonio-flask
    build: ./app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      FLASK_RUN_HOST: 0.0.0.0
      TEMPLATES_AUTO_RELOAD: 'True'
      FLASK_ENV: development
    ports: 
      - '8000:5000'
    # links:
    #   - database
    # depends_on:
    #   - database
    volumes:
      - ./app:/app
    networks:
      - default


  # database:
  #   image: mongo:latest
  #   container_name: antonio-mongo
  #   hostname: antonio-mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 123qwe
  #     MONGO_INITDB_DATABASE: antoniodb
  #   volumes:
  #     - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #     - ./mongo/mongo-volume:/data/db
  #     - ./mongo/mongo-volume/log:/var/log/mongodb/
  #   ports:
  #     - '27017-27019:27017-27019'
  #   networks:
  #     - default
volumes:
  persistent:
